# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-21 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('job', models.CharField(max_length=50, verbose_name='工作')),
                ('friends', models.ManyToManyField(related_name='_passport_friends_+', to='users.Passport')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
