# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-21 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='_passport_friends_+', to='users.Passport'),
        ),
    ]
